

DRIVER_PATH = '/Users/mac/PycharmProjects/pluralsight/project/driver/chromedriver'
URL = 'https://finance.yahoo.com/most-active'
URL_LINK = 'https://finance.yahoo.com/quote/{}/profile?p={}'
FINANCIAL_LINK = 'https://finance.yahoo.com/quote/{}/financials?p={}'
NEWS_LINK = 'https://finance.yahoo.com/quote/{}/?p={}'
STATS_LINK = 'https://finance.yahoo.com/quote/SNDL/key-statistics?p={}'
HTML_PARSER = 'html.parser'
TAG_TABLE = 'table'
TAG_TR = 'tr'
TAG_BODY = 'tbody'
TAG_TD = 'td'
TAG_P = 'p'
TAG_DIV = 'div'
TAG_CLASS = 'class'
TAG_UL = 'ul'
TAG_A = 'a'
TAG_REACTID = 'data-reactid'
TAG_ARIALABEL = 'aria-label'
TAG_LI = 'li'
TAG_HREF = 'href'
TAG_DATATEST = 'data-test'
